# Generated by Django 3.1.1 on 2020-09-18 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitiesDelevery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=200)),
                ('address2', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(max_length=200)),
                ('zip_code', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryDelevery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(choices=[('Usa', 'Usa'), ('Ar', 'Algeria'), ('Fr', 'France'), ('Gr', 'Germania')], max_length=200)),
                ('salary_delevery', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('L', 'livrer'), ('A', 'en attente'), ('P', 'payer'), ('N', 'not pay')], max_length=200)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_address', to='store.citiesdelevery')),
                ('employee_responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employe_responsable', to='accounts.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='DeleveryEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_delevery', models.DateTimeField(auto_now_add=True)),
                ('orders_delevery_not_paid', models.IntegerField()),
                ('orders_delevery_paid', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delevery_employee', to='accounts.customuser')),
                ('palace_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_address', to='store.citiesdelevery')),
            ],
        ),
    ]
