# Generated by Django 3.1.1 on 2020-09-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ['start_date']},
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='selected',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
