# Generated by Django 3.1.1 on 2020-09-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200920_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='selected',
            new_name='order_status',
        ),
        migrations.AlterField(
            model_name='orders',
            name='items',
            field=models.ManyToManyField(related_name='items', to='store.OrderProduct'),
        ),
    ]
