# Generated by Django 3.1.1 on 2020-09-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='auth_token',
            field=models.CharField(default='DUMMY', max_length=12, unique=True),
        ),
    ]
