# Generated by Django 3.1.1 on 2020-09-18 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_auth_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='CilentUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='auth_token',
        ),
    ]
