# Generated by Django 3.1.1 on 2020-09-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Mobil', 'Mobil'), ('Swatch', 'Swatch'), ('Medical', 'Medical'), ('Toys', 'Toys'), ('women_bags', 'women bags'), ('other', 'other')], default='other', max_length=200)),
                ('price_wholesale', models.IntegerField()),
                ('price_detail', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(null=True)),
                ('quantity_min', models.IntegerField(null=True)),
                ('product', models.ManyToManyField(to='shop.Product')),
            ],
        ),
    ]
